using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;


namespace TravelExperts
{
    public partial class frmAddModifyProduct : Form

    {

        public Products Product { get; set; } // selected product on the main form

        public bool AddProduct { get; set; } // flag that distinguishes Add from Modify

        public frmAddModifyProduct()
        {
            InitializeComponent();
        }

        private void frmAddModifyProduct_Load(object sender, EventArgs e)
        {
            if (AddProduct) // this is Add
            {
                this.Text = "Add Product";
                txtProductID.Text = "Product id is AutoGenerated";
                 // allow entry of new product id
            }
            else // this is Modify
            {
                this.Text = "Modify Product";
                txtProductID.ReadOnly = true;   // can't change existing product code
                this.DisplayProduct();
            }
        }

        private void DisplayProduct()
        {
            txtProductID.Text = Product.ProductId.ToString();
            txtProductName.Text = Product.ProdName;
         
        }

        private void btnAccept_Click(object sender, EventArgs e)
        {
            if (IsValidData())
            {

                if (AddProduct) // this is Add
                {
                    // initialize the Product property with new Products object
                    this.Product = new Products();
                }
                this.LoadProductData(); // we have an object (public property Product) with new data
                this.DialogResult = DialogResult.OK;
            }
        }

        private bool IsValidData()
        {
            bool success = true;
            string errorMessage = "";
            //is present
            errorMessage += Validator.IsPresent(txtProductName, "Product Name");
            //errorMessage += Validator.IsPresent(txtProductName.Text, "Product Code");
           
          

            if (errorMessage != "")
            {
                success = false;
                MessageBox.Show(errorMessage, "Entry Error");
            }
            return success;
        }

        private void LoadProductData()
        {
       
            Product.ProdName = txtProductName.Text;
        }

        private void btnCancel_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void txtProductName_TextChanged(object sender, EventArgs e)
        {

        }
    }
}
